services:
  - type: web
    name: dealpro-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DATABASE_URL
        fromDatabase:
          name: dealpro_db
          property: connectionString
    autoDeploy: false

  - type: postgres
    name: dealpro_db
    plan: free
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 15